
export const properties = [
  {
    id: 1,
    title: 'Modern House in Tashkent',
    price: 450000,
    location: 'tashkent',
    type: 'house',
    rooms: 4,
    area: 250,
    description: 'Beautiful modern house with spacious rooms and contemporary design. Features include a large garden, modern kitchen, and excellent natural lighting throughout.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
    imageAlt: 'modern house exterior daylight',
    postedBy: null,
  },
  {
    id: 2,
    title: 'Luxury Apartment Downtown',
    price: 320000,
    location: 'tashkent',
    type: 'apartment',
    rooms: 3,
    area: 180,
    description: 'Stunning apartment in the heart of the city with premium finishes and panoramic views. Close to all amenities and public transportation.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_2.png',
    imageAlt: 'apartment living room interior',
    postedBy: null,
  },
  {
    id: 3,
    title: 'Spacious Villa in Samarkand',
    price: 680000,
    location: 'samarkand',
    type: 'villa',
    rooms: 5,
    area: 400,
    description: 'Exclusive villa with private pool and garden. Perfect for families seeking luxury and comfort in a prestigious neighborhood.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
    imageAlt: 'modern house exterior daylight',
    postedBy: null,
  },
  {
    id: 4,
    title: 'Cozy Apartment in Bukhara',
    price: 180000,
    location: 'bukhara',
    type: 'apartment',
    rooms: 2,
    area: 95,
    description: 'Charming apartment perfect for young professionals or couples. Recently renovated with modern amenities and excellent location.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_4.png',
    imageAlt: 'modern kitchen detail interior',
    postedBy: null,
  },
  {
    id: 5,
    title: 'Contemporary House',
    price: 520000,
    location: 'tashkent',
    type: 'house',
    rooms: 4,
    area: 280,
    description: 'Architecturally designed contemporary home with open-plan living and high-end finishes. Features smart home technology and energy-efficient systems.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_5.png',
    imageAlt: 'abstract geometric blue home shapes',
    postedBy: null,
  },
  {
    id: 6,
    title: 'Family Home in Samarkand',
    price: 390000,
    location: 'samarkand',
    type: 'house',
    rooms: 3,
    area: 220,
    description: 'Perfect family home in a quiet neighborhood. Large backyard, modern kitchen, and close to schools and parks.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
    imageAlt: 'modern house exterior daylight',
    postedBy: null,
  },
  {
    id: 7,
    title: 'Penthouse Apartment',
    price: 750000,
    location: 'tashkent',
    type: 'apartment',
    rooms: 4,
    area: 300,
    description: 'Luxurious penthouse with breathtaking city views. Features include a private terrace, premium appliances, and concierge service.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_2.png',
    imageAlt: 'apartment living room interior',
    postedBy: null,
  },
  {
    id: 8,
    title: 'Charming Villa',
    price: 580000,
    location: 'bukhara',
    type: 'villa',
    rooms: 4,
    area: 350,
    description: 'Beautiful villa with traditional architecture and modern comforts. Includes a courtyard, fountain, and mature gardens.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
    imageAlt: 'modern house exterior daylight',
    postedBy: null,
  },
];