
export const properties = [
  {
    id: 1,
    title: 'Modern House in Tashkent',
    price: 450000,
    location: 'tashkent',
    type: 'house',
    rooms: 4,
    area: 250,
    description: 'Beautiful modern house with spacious rooms and contemporary design. Features include a large garden, modern kitchen, and excellent natural lighting throughout.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
    imageAlt: 'modern house exterior daylight',
    postedBy: null,
  },
  {
    id: 2,
    title: 'Luxury Apartment Downtown',
    price: 320000,
    location: 'tashkent',
    type: 'apartment',
    rooms: 3,
    area: 180,
    description: 'Stunning apartment in the heart of the city with premium finishes and panoramic views. Close to all amenities and public transportation.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_2.png',
    imageAlt: 'apartment living room interior',
    postedBy: null,
  },
  {
    id: 3,
    title: 'Spacious Villa in Samarkand',
    price: 680000,
    location: 'samarkand',
    type: 'villa',
    rooms: 5,
    area: 400,
    description: 'Exclusive villa with private pool and garden. Perfect for families seeking luxury and comfort in a prestigious neighborhood.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
    imageAlt: 'modern house exterior daylight',
    postedBy: null,
  },
  {
    id: 4,
    title: 'Cozy Apartment in Bukhara',
    price: 180000,
    location: 'bukhara',
    type: 'apartment',
    rooms: 2,
    area: 95,
    description: 'Charming apartment perfect for young professionals or couples. Recently renovated with modern amenities and excellent location.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_4.png',
    imageAlt: 'modern kitchen detail interior',
    postedBy: null,
  },
  {
    id: 5,
    title: 'Contemporary House',
    price: 520000,
    location: 'tashkent',
    type: 'house',
    rooms: 4,
    area: 280,
    description: 'Architecturally designed contemporary home with open-plan living and high-end finishes. Features smart home technology and energy-efficient systems.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_5.png',
    imageAlt: 'abstract geometric blue home shapes',
    postedBy: null,
  },
  {
    id: 6,
    title: 'Family Home in Samarkand',
    price: 390000,
    location: 'samarkand',
    type: 'house',
    rooms: 3,
    area: 220,
    description: 'Perfect family home in a quiet neighborhood. Large backyard, modern kitchen, and close to schools and parks.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
    imageAlt: 'modern house exterior daylight',
    postedBy: null,
  },
  {
    id: 7,
    title: 'Penthouse Apartment',
    price: 750000,
    location: 'tashkent',
    type: 'apartment',
    rooms: 4,
    area: 300,
    description: 'Luxurious penthouse with breathtaking city views. Features include a private terrace, premium appliances, and concierge service.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_2.png',
    imageAlt: 'apartment living room interior',
    postedBy: null,
  },
  {
    id: 8,
    title: 'Charming Villa',
    price: 580000,
    location: 'bukhara',
    type: 'villa',
    rooms: 4,
    area: 350,
    description: 'Beautiful villa with traditional architecture and modern comforts. Includes a courtyard, fountain, and mature gardens.',
    image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
    imageAlt: 'modern house exterior daylight',
    postedBy: null,
  },
  {
  id: 9,
  title: 'Modern Apartment in Tashkent City',
  price: 410000,
  location: 'tashkent',
  type: 'apartment',
  rooms: 3,
  area: 170,
  description: 'Modern apartment located in the prestigious Tashkent City area with beautiful skyline views and high-quality finishes.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_2.png',
  imageAlt: 'modern apartment interior',
  postedBy: null,
},
{
  id: 10,
  title: 'Luxury Villa with Pool',
  price: 820000,
  location: 'samarkand',
  type: 'villa',
  rooms: 6,
  area: 450,
  description: 'Luxury villa featuring a private swimming pool, large garden, and spacious living areas perfect for entertaining guests.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
  imageAlt: 'luxury villa exterior',
  postedBy: null,
},
{
  id: 11,
  title: 'Affordable Apartment',
  price: 140000,
  location: 'bukhara',
  type: 'apartment',
  rooms: 2,
  area: 80,
  description: 'Budget-friendly apartment ideal for students or young families with easy access to public transportation.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_4.png',
  imageAlt: 'small apartment kitchen',
  postedBy: null,
},
{
  id: 12,
  title: 'Classic Family House',
  price: 360000,
  location: 'tashkent',
  type: 'house',
  rooms: 4,
  area: 210,
  description: 'Comfortable family house with spacious backyard and quiet neighborhood, ideal for raising children.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
  imageAlt: 'family house exterior',
  postedBy: null,
},
{
  id: 13,
  title: 'Modern Studio Apartment',
  price: 120000,
  location: 'tashkent',
  type: 'apartment',
  rooms: 1,
  area: 55,
  description: 'Compact and stylish studio apartment with modern design and excellent city location.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_2.png',
  imageAlt: 'studio apartment interior',
  postedBy: null,
},
{
  id: 14,
  title: 'Traditional House in Samarkand',
  price: 300000,
  location: 'samarkand',
  type: 'house',
  rooms: 3,
  area: 200,
  description: 'Traditional Uzbek-style house with courtyard and beautiful architectural details.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
  imageAlt: 'traditional house exterior',
  postedBy: null,
},
{
  id: 15,
  title: 'Premium Penthouse',
  price: 910000,
  location: 'tashkent',
  type: 'apartment',
  rooms: 5,
  area: 420,
  description: 'Ultra-luxury penthouse with private elevator access and stunning panoramic views of the city.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_2.png',
  imageAlt: 'luxury penthouse interior',
  postedBy: null,
},
{
  id: 16,
  title: 'Garden Villa',
  price: 610000,
  location: 'bukhara',
  type: 'villa',
  rooms: 4,
  area: 330,
  description: 'Elegant villa surrounded by lush gardens and peaceful outdoor spaces.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
  imageAlt: 'villa with garden',
  postedBy: null,
},
{
  id: 17,
  title: 'Compact City Apartment',
  price: 200000,
  location: 'tashkent',
  type: 'apartment',
  rooms: 2,
  area: 90,
  description: 'Modern apartment perfect for city living with easy access to shopping malls and restaurants.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_2.png',
  imageAlt: 'city apartment living room',
  postedBy: null,
},
{
  id: 18,
  title: 'Large Country House',
  price: 470000,
  location: 'samarkand',
  type: 'house',
  rooms: 5,
  area: 310,
  description: 'Spacious countryside house with beautiful landscape and peaceful environment.',
  image: 'https://c.animaapp.com/mmiqugmsQ6jTJx/img/ai_1.png',
  imageAlt: 'country house exterior',
  postedBy: null,
}, {
  id: 19,
  title: 'Luxury Glass House',
  price: 860000,
  location: 'tashkent',
  type: 'house',
  rooms: 5,
  area: 420,
  description: 'Modern glass house with panoramic windows and minimalistic architecture. Located in a premium district.',
  image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
  imageAlt: 'luxury modern glass house',
  postedBy: null,
},
{
  id: 20,
  title: 'Elegant City Apartment',
  price: 275000,
  location: 'tashkent',
  type: 'apartment',
  rooms: 3,
  area: 150,
  description: 'Elegant apartment in the city center with modern interior design and comfortable layout.',
  image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
  imageAlt: 'modern apartment interior',
  postedBy: null,
},
{
  id: 21,
  title: 'Luxury Villa Residence',
  price: 940000,
  location: 'samarkand',
  type: 'villa',
  rooms: 6,
  area: 500,
  description: 'Exclusive villa residence with a large swimming pool and luxurious outdoor terrace.',
  image: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6',
  imageAlt: 'luxury villa with pool',
  postedBy: null,
},
{
  id: 22,
  title: 'Minimalist Apartment',
  price: 210000,
  location: 'bukhara',
  type: 'apartment',
  rooms: 2,
  area: 100,
  description: 'Minimalist apartment with bright natural lighting and open living space.',
  image: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6',
  imageAlt: 'minimalist apartment interior',
  postedBy: null,
},
{
  id: 23,
  title: 'Modern Family House',
  price: 480000,
  location: 'tashkent',
  type: 'house',
  rooms: 4,
  area: 260,
  description: 'Perfect modern family house with spacious garden and beautiful outdoor area.',
  image: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6',
  imageAlt: 'modern family house',
  postedBy: null,
},
{
  id: 24,
  title: 'Elegant Traditional Villa',
  price: 610000,
  location: 'samarkand',
  type: 'villa',
  rooms: 4,
  area: 340,
  description: 'Beautiful traditional villa with elegant architecture and peaceful courtyard.',
  image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811',
  imageAlt: 'traditional villa exterior',
  postedBy: null,
},
{
  id: 25,
  title: 'Modern Loft Apartment',
  price: 295000,
  location: 'tashkent',
  type: 'apartment',
  rooms: 2,
  area: 130,
  description: 'Stylish loft apartment with industrial design and high ceilings.',
  image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
  imageAlt: 'modern loft apartment',
  postedBy: null,
},
{
  id: 26,
  title: 'Garden View House',
  price: 390000,
  location: 'bukhara',
  type: 'house',
  rooms: 3,
  area: 210,
  description: 'Comfortable house with beautiful garden view and quiet neighborhood.',
  image: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c',
  imageAlt: 'house with garden',
  postedBy: null,
},
{
  id: 27,
  title: 'Luxury Skyline Penthouse',
  price: 990000,
  location: 'tashkent',
  type: 'apartment',
  rooms: 5,
  area: 460,
  description: 'Luxury penthouse with breathtaking skyline views and premium amenities.',
  image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
  imageAlt: 'luxury penthouse skyline view',
  postedBy: null,
},
{
  id: 28,
  title: 'Countryside Villa',
  price: 540000,
  location: 'samarkand',
  type: 'villa',
  rooms: 4,
  area: 320,
  description: 'Peaceful countryside villa surrounded by nature and fresh air.',
  image: 'https://images.unsplash.com/photo-1600585152915-d208bec867a1',
  imageAlt: 'countryside villa exterior',
  postedBy: null,
}
];